# Generated by Django 5.2.8 on 2025-11-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_id', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('size_m', models.IntegerField(blank=True, help_text='Размер карты в метрах, например 1000', null=True)),
                ('layout_type', models.CharField(blank=True, choices=[('open', 'Открытая'), ('city', 'Городская'), ('mixed', 'Смешанная')], max_length=20, null=True)),
                ('wg_type', models.CharField(blank=True, choices=[('summer', 'Летняя'), ('winter', 'Зимняя'), ('desert', 'Пустынная')], max_length=20, null=True)),
            ],
        ),
    ]
